version: '3.9'

services:
  # PostgreSQL Database Service
  warehouse_db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
    ports:
      - "5432:5432"
    volumes:
      - postgres-volume:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d

  # Airflow DB for Airflow Metadata
  airflow-db:
    image: postgres:15
    environment:
      POSTGRES_DB: airflow
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  # Redis Service for Airflow
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"

  # Airflow Database Initialization Service
  airflow-init:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-db
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-db/airflow"
    command: "airflow db init"

  # Airflow Webserver Service
  airflow-webserver:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-init
      - redis
    environment:
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-db/airflow"
      AIRFLOW__WEBSERVER__EXPOSE_CONFIG: "True"
      AIRFLOW__CORE__FERNET_KEY: "3XHYF2ThlHV63zcCL6FoOzklKdxjkxQcRTJuHr0w634=" # Replace with a generated key
      AIRFLOW__WEBSERVER__SECRET_KEY: "3XHYF2ThlHV63zcCL6FoOzklKdxjkxQcRTJuHr0w634=" # Replace with a generated key
      AIRFLOW__WEBSERVER__SECRET_KEY_CMD: "3XHYF2ThlHV63zcCL6FoOzklKdxjkxQcRTJuHr0w634"
      _AIRFLOW_WWW_USER_USERNAME: "admin"  # Nom d'utilisateur
      _AIRFLOW_WWW_USER_PASSWORD: "admin"  # Mot de passe
      GUNICORN_CMD_ARGS: "--timeout 300"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
    ports:
      - "8080:8080"
    command: "webserver"

  # Airflow Scheduler Service
  airflow-scheduler:
    image: apache/airflow:2.7.0
    depends_on:
      - airflow-init
      - airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: "LocalExecutor"
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://airflow:airflow@airflow-db/airflow"
    volumes:
      - ./dags:/opt/airflow/dags
    command: "scheduler"

  # Metabase Service
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    hostname: metabase
    volumes:
    - urandom:/dev/random:ro
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres-volume:
  airflow_db_data:
  urandom:
